sequenceDiagram
autonumber
actor User
participant TodoConsole
participant InputValidator
participant TaskService
participant TaskRepository
participant TasksJson as "tasks.json"


User->>TodoConsole: Select "View Tasks"
TodoConsole->>TaskService: getTasks()
TaskService-->>TodoConsole: vector<Task>
TodoConsole-->>User: display ID, description, completion status
