sequenceDiagram
autonumber
actor User
participant TodoConsole
participant InputValidator
participant TaskService
participant TaskRepository
participant TasksJson as "tasks.json"


User->>TodoConsole: Select "Exit"
TodoConsole-->>User: terminate application
